module.exports = {
  colorone: {
    CTABackground: '#2964d8',
    CTAText: 'white',
    HomepagePromoBackground: '#fbf0e7',
    HomepagePromoText: 'black',
    PromoBlockBackground: '#2964d8',
    PromoBlockText: 'white',
    PromoBlockCTABackground: 'white',
    PromoBlockCTAText: '#2964d8',
    DescriptorColor: '#2964d8',
  },
  colortwo: {
    CTABackground: '#0f3542',
    CTAText: 'white',
    HomepagePromoBackground: '#cedcba',
    HomepagePromoText: 'black',
    PromoBlockBackground: '#cedcba',
    PromoBlockText: 'black',
    PromoBlockCTABackground: '#0f3542',
    PromoBlockCTAText: 'white',
    DescriptorColor: '#0f3542',
  },
  colorthree: {
    CTABackground: 'black',
    CTAText: 'white',
    HomepagePromoBackground: '#e7e5e4',
    HomepagePromoText: 'black',
    PromoBlockBackground: 'black',
    PromoBlockText: 'white',
    PromoBlockCTABackground: 'white',
    PromoBlockCTAText: 'black',
    DescriptorColor: 'black',
  },
};
