module.exports = {
  styleone: {
    ArticleDescriptor: 'Libre Franklin',
    ArticleHeader: 'Libre Franklin',
    AdvertiseLink: 'Libre Franklin',
    ArticleDek: 'Libre Franklin',
    PublishDate: 'Libre Franklin',
    ArticleMetaTop: 'Libre Franklin',
    Caption: 'Libre Franklin',
    SectionLink: 'Libre Franklin',
    DonateLink: 'Libre Franklin',
    HomepagePromoBlockHeader: 'Libre Franklin',
    HomepagePromoBlockDek: 'Libre Franklin',
    HomepagePromoBlockCTA: 'Libre Franklin',
    PromotionBlockHed: 'Libre Franklin',
    PromotionBlockDek: 'Libre Franklin',
    PromotionBlockCTA: 'Libre Franklin',
  },
  styletwo: {
    ArticleDescriptor: 'Source Sans Pro',
    ArticleHeader: 'Source Serif Pro',
    ArticleDek: 'Source Sans Pro',
    AdvertiseLink: 'Source Sans Pro',
    PublishDate: 'Source Sans Pro',
    ArticleMetaTop: 'Source Sans Pro',
    Caption: 'Source Sans Pro',
    SectionLink: 'Source Sans Pro',
    DonateLink: 'Source Sans Pro',
    HomepagePromoBlockHeader: 'Source Serif Pro',
    HomepagePromoBlockDek: 'Source Sans Pro',
    HomepagePromoBlockCTA: 'Source Sans Pro',
    PromotionBlockHed: 'Source Serif Pro',
    PromotionBlockDek: 'Source Sans Pro',
    PromotionBlockCTA: 'Source Sans Pro',
  },
  stylethree: {
    ArticleDescriptor: 'Roboto',
    ArticleHeader: 'Roboto Condensed',
    ArticleDek: 'Roboto',
    PublishDate: 'Roboto',
    ArticleMetaTop: 'Roboto',
    Caption: 'Roboto',
    SectionLink: 'Roboto',
    DonateLink: 'Roboto',
    HomepagePromoBlockHeader: 'Roboto Condensed',
    HomepagePromoBlockDek: 'Roboto',
    HomepagePromoBlockCTA: 'Roboto',
    PromotionBlockHed: 'Roboto Condensed',
    PromotionBlockDek: 'Roboto',
    PromotionBlockCTA: 'Roboto',
  },
  stylefour: {
    ArticleDescriptor: 'Mulish',
    ArticleHeader: 'Arbutus Slab',
    ArticleDek: 'Mulish',
    AdvertiseLink: 'Mulish',
    PublishDate: 'Mulish',
    ArticleMetaTop: 'Mulish',
    Caption: 'Mulish',
    SectionLink: 'Mulish',
    DonateLink: 'Mulish',
    HomepagePromoBlockHeader: 'Arbutus Slab',
    HomepagePromoBlockDek: 'Mulish',
    HomepagePromoBlockCTA: 'Mulish',
    PromotionBlockHed: 'Arbutus Slab',
    PromotionBlockDek: 'Mulish',
    PromotionBlockCTA: 'Mulish',
  },
  stylefive: {
    ArticleDescriptor: 'Lato',
    ArticleHeader: 'Bodoni Moda',
    ArticleDek: 'Lato',
    PublishDate: 'Lato',
    ArticleMetaTop: 'Lato',
    Caption: 'Lato',
    SectionLink: 'Lato',
    DonateLink: 'Lato',
    AdvertiseLink: 'Lato',
    HomepagePromoBlockHeader: 'Bodoni Moda',
    HomepagePromoBlockDek: 'Lato',
    HomepagePromoBlockCTA: 'Lato',
    PromotionBlockHed: 'Arbutus Slab',
    PromotionBlockDek: 'Mulish',
    PromotionBlockCTA: 'Mulish',
  },
};
