module.exports = {
  siteMetadata: {
    shortName: `The Oaklyn Observer`,
    siteUrl: `https://tinynewsco.org/`,
    homepageTitle: `The Oaklyn Observer`,
    homepageSubtitle: `a local news initiative`,
    subscribe: {
      title: `Subscribe`,
      subtitle: `Get the latest news about the tiny news collective in your inbox.`,
    },
    footerTitle: `tinynewsco.org`,
    footerBylineName: `News Catalyst`,
    footerBylineLink: `https://newscatalyst.org`,
    labels: {
      latestNews: `Latest News`,
      search: `Search`,
      topics: `Topics`,
    },
    nav: {
      articles: `Articles`,
      topics: `All Topics`,
      cms: `tinycms`,
    },
    searchTitle: `The Oaklyn Observer`,
    searchDescription: `Page description`,
    facebookTitle: `Facebook title`,
    facebookDescription: `Facebook description`,
    twitterTitle: `Twitter title`,
    twitterDescription: `Twitter description`,
    firstPublishedOn: null,
    lastPublishedOn: null,
    tags: null,
    coverImage: null,
  },
};
