name: GA Data Importer
'on':
  schedule:
    - cron: 5 9 * * *
jobs:
  GA-Data-Importer:
    runs-on: ubuntu-latest
    environment: data_import_bello
    steps:
      - run: echo "🔎 Running GA data importer"
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: echo "🖥️ repo and node are setup"
      - name: install node-fetch
        run: npm install node-fetch
      - name: install dotenv
        run: npm install dotenv
      - name: install date-fns
        run: npm install date-fns
      - name: run data importer
        env:
          NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
          HASURA_API_URL: ${{ secrets.HASURA_API_URL }}
          ORG_SLUG: ${{ secrets.ORG_SLUG }}
          GOOGLE_CREDENTIALS_EMAIL: ${{ secrets.GOOGLE_CREDENTIALS_EMAIL }}
          GOOGLE_CREDENTIALS_PRIVATE_KEY: ${{ secrets.GOOGLE_CREDENTIALS_PRIVATE_KEY }}
          NEXT_PUBLIC_ANALYTICS_VIEW_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_VIEW_ID }}
        run: npm run data:import
      - run: echo "🍏 This job's status is ${{ job.status }}."
