name: Cypress Tests
on: [push]
jobs:
  install:
    name: Build and upload front-end site
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    environment: data_import_oaklyn
    env:
      LOCALES: ${{ secrets.LOCALES }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      HASURA_API_URL: ${{ secrets.HASURA_API_URL }}
      ORG_SLUG: ${{ secrets.ORG_SLUG }}
      GOOGLE_CREDENTIALS_EMAIL: ${{ secrets.GOOGLE_CREDENTIALS_EMAIL }}
      GOOGLE_CREDENTIALS_PRIVATE_KEY: ${{ secrets.GOOGLE_CREDENTIALS_PRIVATE_KEY }}
      NEXT_PUBLIC_ANALYTICS_VIEW_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_VIEW_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on linux/macos
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: .next
  cypress-run:
    name: Run Cypress tests
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    environment: data_import_oaklyn
    env:
      LOCALES: ${{ secrets.LOCALES }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      HASURA_API_URL: ${{ secrets.HASURA_API_URL }}
      ORG_SLUG: ${{ secrets.ORG_SLUG }}
      GOOGLE_CREDENTIALS_EMAIL: ${{ secrets.GOOGLE_CREDENTIALS_EMAIL }}
      GOOGLE_CREDENTIALS_PRIVATE_KEY: ${{ secrets.GOOGLE_CREDENTIALS_PRIVATE_KEY }}
      NEXT_PUBLIC_ANALYTICS_VIEW_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_VIEW_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .next
      - name: restore cached node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on linux/macos
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashfiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: 'UI Tests - Firefox'
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox'