name: Cypress Tests
on: [push]
jobs:
  install:
    name: Build and upload front-end site
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    environment: data_import_oaklyn
    env:
      LOCALES: ${{ secrets.LOCALES }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      HASURA_API_URL: ${{ secrets.HASURA_API_URL }}
      ORG_SLUG: ${{ secrets.ORG_SLUG }}
      GOOGLE_CREDENTIALS_EMAIL: ${{ secrets.GOOGLE_CREDENTIALS_EMAIL }}
      GOOGLE_CREDENTIALS_PRIVATE_KEY: ${{ secrets.GOOGLE_CREDENTIALS_PRIVATE_KEY }}
      NEXT_PUBLIC_ANALYTICS_VIEW_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_VIEW_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-dir
          # loading an older version is fine here, since it will get an npm install
          restore-keys: |
            npm-dir-
      - name: Cache cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cached-cypress-binary
          restore-keys: |
            cached-cypress-binary-
      - name: npm ci
        run: npm ci
      - name: Cypress install
        uses: cypress-io/github-action@v2
        with:
          # Disable running of tests within install job
          runTests: false
          build: npm run build
      - name: Save build folder
        uses: actions/upload-artifact@v2
        with:
          name: build
          if-no-files-found: error
          path: .next
  cypress-run:
    name: Run Cypress tests
    needs: install
    strategy:
      fail-fast: false
      matrix:
        # run copies of the current job in parallel
        containers: [1, 2, 3, 4, 5]
    runs-on: ubuntu-latest
    container: 
      image: cypress/browsers:node14.16.0-chrome89-ff86
      options: --user 1001
    environment: data_import_oaklyn
    env:
      LOCALES: ${{ secrets.LOCALES }}
      NEXT_PUBLIC_SITE_URL: ${{ secrets.NEXT_PUBLIC_SITE_URL }}
      HASURA_API_URL: ${{ secrets.HASURA_API_URL }}
      ORG_SLUG: ${{ secrets.ORG_SLUG }}
      GOOGLE_CREDENTIALS_EMAIL: ${{ secrets.GOOGLE_CREDENTIALS_EMAIL }}
      GOOGLE_CREDENTIALS_PRIVATE_KEY: ${{ secrets.GOOGLE_CREDENTIALS_PRIVATE_KEY }}
      NEXT_PUBLIC_ANALYTICS_VIEW_ID: ${{ secrets.NEXT_PUBLIC_ANALYTICS_VIEW_ID }}
      CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      CYPRESS_PROJECT_ID: ${{ secrets.CYPRESS_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Load node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: npm-dir
          # no restore-keys here, so we only accept this exact version
      - name: Load cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: cached-cypress-binary
      - name: Download the build folders
        uses: actions/download-artifact@v2
        with:
          name: build
          path: .next
      - name: Install dependencies
        run: npm ci
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: 'UI Tests - Firefox'
        uses: cypress-io/github-action@v2
        with:
          install: false
          start: npm run start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
          browser: firefox
          record: true
          parallel: true
          group: 'UI - Firefox'